### PR TITLE
Issue #213. Avalon would crash when destroying MediaObjects / MasterFiles

### LINKED ISSUE #213: NoMethodError: undefined method `cancel!' for nil:NilClass
View details in Rollbar: [https://rollbar.com/ualbertalib/avalon/items/30/](https://rollbar.com/ualbertalib/avalon/items/30/)

```

NoMethodError: undefined method `cancel!' for nil:NilClass
  File "/var/www/avalon/app/models/master_file.rb", line 178, in destroy
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/active-fedora-8.1.0/lib/active_fedora/relation/delegation.rb", line 10, in each
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/active-fedora-8.1.0/lib/active_fedora/relation/delegation.rb", line 10, in each
  File "/var/www/avalon/app/models/media_object.rb", line 222, in destroy
  File "/var/www/avalon/app/models/media_object.rb", line 689, in block in delete_bulk
  File "/var/www/avalon/app/models/media_object.rb", line 687, in each
  File "/var/www/avalon/app/models/media_object.rb", line 687, in delete_bulk
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/performable_method.rb", line 26, in perform
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb", line 84, in block in invoke_job
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/rollbar-2.15.0/lib/rollbar/plugins/delayed_job/plugin.rb", line 35, in block in invoke_job_callback
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 79, in block (2 levels) in add
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 61, in block in initialize
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 79, in block in add
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 66, in execute
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 40, in run_callbacks
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb", line 81, in invoke_job
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 230, in block (2 levels) in run
  File "/usr/lib64/ruby/2.3.0/timeout.rb", line 91, in block in timeout
  File "/usr/lib64/ruby/2.3.0/timeout.rb", line 101, in timeout
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 230, in block in run
  File "/usr/lib64/ruby/2.3.0/benchmark.rb", line 308, in realtime
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 229, in run
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 306, in block in reserve_and_run_one_job
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 61, in block in initialize
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 66, in execute
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 40, in run_callbacks
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 306, in reserve_and_run_one_job
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 213, in block in work_off
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 212, in times
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 212, in work_off
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 175, in block (4 levels) in start
  File "/usr/lib64/ruby/2.3.0/benchmark.rb", line 308, in realtime
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 174, in block (3 levels) in start
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 61, in block in initialize
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 66, in execute
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 40, in run_callbacks
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 173, in block (2 levels) in start
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 172, in loop
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 172, in block in start
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/plugins/clear_locks.rb", line 7, in block (2 levels) in <class:ClearLocks>
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 79, in block (2 levels) in add
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 61, in block in initialize
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 79, in block in add
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 66, in execute
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb", line 40, in run_callbacks
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb", line 171, in start
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/command.rb", line 132, in run
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/command.rb", line 120, in block in run_process
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb", line 266, in block in start_proc
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/daemonize.rb", line 84, in call_as_daemon
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb", line 270, in start_proc
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb", line 296, in start
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/controller.rb", line 56, in run
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons.rb", line 197, in block in run_proc
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/cmdline.rb", line 92, in catch_exceptions
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons.rb", line 196, in run_proc
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/command.rb", line 118, in run_process
  File "/var/www/avalon/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/command.rb",

### PR DESCRIPTION
**Pull request by cwant**
Issue #213. Avalon would crash when destroying MediaObjects / MasterFiles when the masterfiles had hung encode jobs. This was due to some missing nil checking in MasterFile#destroy.
Also created a test suite for MasterFile#destroy.

This was reported by Rollbar here: 

https://rollbar.com/ualbertalib/avalon/items/30/

Fixes #213

### CODE REVIEW

File: app/models/master_file.rb [hunk 1]
```diff
@@ -175,7 +175,8 @@ def destroy
 
     # Stops all processing
     if workflow_id.present? && !finished_processing?
-      encoder_class.find(workflow_id).cancel!
+      encoding_job = encoder_class.find(workflow_id)
+      encoding_job.cancel! if encoding_job
```
Comment (murny) [inline app/models/master_file.rb]: you can make this cleaner by using ruby's `.try` method if you want just FYI

```ruby
encoder_class.find(workflow_id).try(:cancel!)
```
or if you want to use ruby 2.3 syntax the `&.` also does this

```ruby
encoder_class.find(workflow_id)&.(:cancel!)
```
more info here: http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/

Route issue though is `.find()` behaviour unlike ActiveRecord. Assuming this is activefedora or something? ActiveRecord would have raised an RecordNotFound exception on a bad find instead of returning nil

Comment (cwant) [inline app/models/master_file.rb]: Cheers, have opted for the &. (safe navigation operator).
