### PR TITLE
Issue #60, fix the editor role so that it can unpublish.

### LINKED ISSUE #60: editor role is not working properly
### Descriptive summary

When we assign someone as an editor, the user is not able to make changes in the metadata

### Expected behavior
A user assigned with "editor" role for a particular collection should be able to make changes to metadata.

### Actual behavior
Currently an "editor" is not able to make metadata changes and save them. To overcome this, we have been assigning "manager" role which give them more power than we would like.

### Related work

#61

### PR DESCRIPTION
**Pull request by cwant**
The previous fix (which was to allow both managers and now editors to
unpublish items) didn't take into account that some controllers had  additional
logic for unpublishing (they also required that the user can update the object, which
an editor can't do on a published object).

I took the opportunity to clean up the media objects controller (primarily affecting single items)
and bookmarks controller (bulk operations) for the relevant actions.

I expanded the test suites for the relevant controllers to include testing of the
editor permissions.

I also made the controller methods share I18n translations better (some output
wasn't using I18n).

Fixes #60

### CODE REVIEW

File: app/controllers/bookmarks_controller.rb [hunk 1]
```diff
@@ -132,23 +132,27 @@ def status_action documents
     status = params['action']
     Array(documents.map(&:id)).each do |id|
       media_object = MediaObject.find(id)
-      if cannot? :update, media_object
-        errors += ["#{media_object.title} (#{id}) #{t('blacklight.messages.permission_denied')}."]
+      sucess = false
+      case status
```
Comment (murny) [inline app/controllers/bookmarks_controller.rb]: This logic needs refactoring? Forcing a switch statement and a flag when a simple if else could do?

```ruby 

if status.publish || status.unpublish
  success_ids << id if can?(:update, media_object) || can?(:unpublish, media_object)
else
  errors << #{media_object.title} (#{id}) #{t('blacklight.messages.permission_denied')}."
end
```

Comment (murny) [inline app/controllers/bookmarks_controller.rb]: You could even tajke this further and put the flash logic in those if else blocks? Why do array checks later on?

File: app/controllers/bookmarks_controller.rb [hunk 2]
```diff
@@ -132,23 +132,27 @@ def status_action documents
...
       end
     end
-    flash[:success] = t("blacklight.status.success", count: success_ids.count, status: status) if success_ids.count > 0
-    flash[:alert] = "#{t('blacklight.status.alert', count: errors.count, status: status)}</br> #{ errors.join('<br/> ') }".html_safe if errors.count > 0
+    flash[:success] =
+      "#{t("blacklight.status.success", count: success_ids.count, status: status)} "\
+      "#{t('blacklight.status.bulk_warning')}" if success_ids.count > 0
+    flash[:alert] = 
+      "#{t('blacklight.status.alert', count: errors.count, status: status)} "\
+      "</br> #{ errors.join('<br/> ') }".html_safe if errors.count > 0
```
Comment (murny) [inline app/controllers/bookmarks_controller.rb]: How bad will this flash message look if theres a tons of errors? Would setting a simply flash and then setting an @errors var which you can use to display those errors properly on the page be a better idea? (in a ul/li bulletted list or something?)

File: app/controllers/media_objects_controller.rb [hunk 3]
```diff
@@ -296,27 +296,34 @@ def update_status
...
-            success_count += 1
-          when 'unpublish'
-            if can? :unpublish, media_object
-              media_object.publish!(nil)
-              success_count += 1
-            else
-              errors += ["#{media_object.title} (#{id}) (permission denied)."]
-            end
+      success = false
+      case status
```
Comment (murny) [inline app/controllers/media_objects_controller.rb]: Would clean this logic up as well. Extremely complicated. Could probably just do all this in a simple `if/elsif/else` statement?

File: app/controllers/media_objects_controller.rb [hunk 4]
```diff
@@ -296,27 +296,34 @@ def update_status
...
+        success_count += 1
+      else
+        errors <<
+          "#{media_object.title} (#{id}) #{t('blacklight.messages.permission_denied')}."
+      end
     end
-    message = "#{success_count} #{'media object'.pluralize(success_count)} successfully #{status}ed."
-    message += "These objects were not #{status}ed:</br> #{ errors.join('<br/> ') }" if errors.count > 0
+    message = "#{success_count} #{'media object'.pluralize(success_count)} "\
+      "successfully #{status}ed."
```
Comment (murny) [inline app/controllers/media_objects_controller.rb]: Would i18n this like the errors are done. pass in the count/status and render the i18n. Instead of string interpolating this. This is also done in a few other places.

File: app/controllers/bookmarks_controller.rb (hunk 1 above)
Comment (cwant) [inline app/controllers/bookmarks_controller.rb]: I guess I disagree will this. What you propose works and uses fewer lines, but it assumes that those who can 'update' and those that can 'unpublish' are doing the same thing (true today, but might break in the future). I would rather have the unpublish activity tied to somebody who can 'unpublish', and the publish activity tied to somebody who can 'update' (would really have preferred it if it was tied to an ability called 'publish', but yeah I'm just working with what's there).

(Looking a few lines above this, I see I have assigned a variable called 'sucess'. Good thing nil is falsey ...)

Comment (murny) [inline app/controllers/bookmarks_controller.rb]: Then i would say break those out into an If elsif else like so: 

```ruby
if status.publish 
  success_ids << id if can?(:update, media_object)
elsif status.unpublish
  success_ids << id if can?(:unpublish, media_object)
else
  errors << #{media_object.title} (#{id}) #{t('blacklight.messages.permission_denied')}."
end
```

Regardless this is much simplier. Don't force a switch statement when you don't need it.

File: app/controllers/media_objects_controller.rb (hunk 4 above)
Comment (cwant) [inline app/controllers/media_objects_controller.rb]: Yeah, it's pretty bad. Missed this one when cleaning up i18n.

File: app/controllers/bookmarks_controller.rb (hunk 2 above)
Comment (cwant) [inline app/controllers/bookmarks_controller.rb]: Good point. On the plus side, I didn't write the code this is based on. :smile: 
Will sanitize.

File: app/controllers/bookmarks_controller.rb (hunk 1 above)
Comment (cwant) [inline app/controllers/bookmarks_controller.rb]: Just out of curiosity, above you are typing "status.publish" instead of "status == 'publish'". Is that a typo, or some kind of ruby/rails magic?

Comment (murny) [inline app/controllers/bookmarks_controller.rb]: A typo

File: app/controllers/bookmarks_controller.rb (hunk 2 above)
Comment (cwant) [inline app/controllers/bookmarks_controller.rb]: Boy, another thing that's pretty bad about this: status is either 'publish' or 'unpublish', which gets fed as a parameter into a translation string. This of course assumes that the language you are translating to has the words 'publish' and 'unpublish' in it  ... :nauseated_face: 
(This would be another moment where I remind the reader that I wasn't the original author of this code)

Comment (cwant) [inline app/controllers/bookmarks_controller.rb]: This is dealt with in the latest commit.

File: app/controllers/bookmarks_controller.rb (hunk 1 above)
Comment (cwant) [inline app/controllers/bookmarks_controller.rb]: This is dealt with (implemented as if/elsif/else).

File: app/controllers/media_objects_controller.rb (hunk 4 above)
Comment (cwant) [inline app/controllers/media_objects_controller.rb]: This is reworked as i18n in the latest commit.

File: app/controllers/media_objects_controller.rb (hunk 3 above)
Comment (cwant) [inline app/controllers/media_objects_controller.rb]: Dealt with in lastest commit

**Comment by cwant** [comment]
@murny Thanks for reviewing -- requested changes have been made, please take a moment to re-review when you have time.

**Comment by seanluyk** [comment]
@cwant is it possible to verify this on dev or test? Just want to make sure that functionality is confirmed before we set up any users with editor permissions. I can also wait and test on prod, too

**Comment by cwant** [comment]
@seanluyk I have deployed to the test server and have verified. I'll send you an email with instructions so that you can verify as well with an unprivileged user.

File: app/controllers/bookmarks_controller.rb [hunk 5]
```diff
@@ -132,23 +132,22 @@ def status_action documents
     status = params['action']
     Array(documents.map(&:id)).each do |id|
       media_object = MediaObject.find(id)
-      if cannot? :update, media_object
-        errors += ["#{media_object.title} (#{id}) #{t('blacklight.messages.permission_denied')}."]
+      if status == 'publish'
+        success_ids << id if can?(:update, media_object)
```
Comment (murny) [inline app/controllers/bookmarks_controller.rb]: what happens if you cannot update media object and you get to here (and same thing for unpublish)?

This logic will fall all the way down to line 151 `MediaObject.update_status_bulk success_ids, current_user.user_key, params`

With no flashes or success_ids/errors set?

(or maybe im confused and cancan will raise an exception here and will get caught somewhere and displayed an authorized flash message or something?)

File: app/controllers/media_objects_controller.rb [hunk 6]
```diff
@@ -296,27 +297,26 @@ def update_status
...
       media_object = MediaObject.find(id)
-      if cannot? :update, media_object
-        errors += ["#{media_object.title} (#{id}) (permission denied)."]
+
+      if (status == 'publish') && can?(:update, media_object)
+        media_object.publish!(user_key)
+        # additional save to set permalink
+        media_object.save(validate: false)
+        success_count += 1
+      elsif (status == 'unpublish') and can?(:unpublish, media_object)
```
Comment (murny) [inline app/controllers/media_objects_controller.rb]: keep consistent and use `&&` instead of `and`?

Comment (mbarnett) [inline app/controllers/media_objects_controller.rb]: `and` has weird precedence too. It's the landmine of Ruby logic

File: app/controllers/bookmarks_controller.rb (hunk 5 above)
Comment (murny) [inline app/controllers/bookmarks_controller.rb]: ah its in the loop...so bascially for that item it just gets skipped over with no messaging etc. Is that desired?

File: app/controllers/media_objects_controller.rb (hunk 6 above)
Comment (cwant) [inline app/controllers/media_objects_controller.rb]: Yeah, I hate `and` (I've been bit by the precedence with the equals sign, which I think they stole from perl). No clue why I have `and` here, will remove.

File: app/controllers/bookmarks_controller.rb (hunk 5 above)
Comment (cwant) [inline app/controllers/bookmarks_controller.rb]: The assumption here is that the person might have selected some MediaObjects they can update, some they can't. For the ones they can change, they will update (publish/unpublish) and show a notice via flash, the ones that can't will have the error reported via flash. (This is logic that pre-dates this patch, btw.). I hope I've understood your question.

Comment (murny) [inline app/controllers/bookmarks_controller.rb]: So with this current logic above, the user wouldn't get any error flash saying they cant update these. They'd just get shown nothing. Only way they get an error flash saying they dont have permission is if the mediaobject isn't in a published/unpublished state

Comment (cwant) [inline app/controllers/bookmarks_controller.rb]: Sure they would get a flash message (alert not error) listing the errors for all of the items being updated, and a flash message listing the successes. Not sure how you are deducing that.

Comment (murny) [inline app/controllers/bookmarks_controller.rb]: That is best case. But worst case you will get a page with no flash messages. Heres an example of best case:

Lets assume you got 3 media objects (one published, one unpublished and one of another status...like unavailable). The user has permission to unpublish/publish these objects. Therefore you will get two flash messages. One with success and one with alerts. Which is what you expect to happen as you described above.

Now worst case, lets say I got three media objects. Two published and one unpublished. The user has no permissions to any of these objects. So what will happen, first object is grabbed, it will hit the `if status == publish` block, its true, so it will go into the block, it will check if I got permission? I don't. Thefore it exits the if statement and fall all the way until the end of the `each` block. And it will then proceed to grab the next element. Same thing happens. Next element? It will do the unpublished block but same thing also happens. Now theres no more elements left in the each, so it will exit out. It will try to create the flash messages, but since `errors.count > 0` and `success_ids.count > 0` are both false no flash messages are created.  So as pointed out above, therefore the user gets no flash message and they get shown nothing. Is this a desired behaviour?

Comment (cwant) [inline app/controllers/bookmarks_controller.rb]: Okay, will restructure to use '&&'. That should ensure that nothing falls between the cracks.

Comment (cwant) [inline app/controllers/bookmarks_controller.rb]: Pushed now ...

**Comment by cwant** [comment]
Thanks!

**Comment by seanluyk** [comment]
@cwant @umarqasim not urgent but just reporting that an editor was not able to unpublish an item so they could edit it. It appears that the edit button/manage content menu only appeared when they were given the manager role. The collection in question is Nosotros.
