### PR TITLE
Issue #168. Create dropbox directory with group write permissions.

### LINKED ISSUE #168: dropbox access for new collections
### Descriptive summary

When the Avalon code creates the directory/folder for the dropbox location whenever a new collection is added it needs to create with the "group writable" attribute.

### Expected behavior
When a new collection is created, the system should create it with "group writable" attribute so that the repository managers can assign permissions themselves.

### Actual behavior
Currently a system admin needs to allow write access whenever a new collection is created

### Steps to reproduce the behavior

1. Create a new collection
2. Try to access it via the repository admin interface

### PR DESCRIPTION
**Pull request by cwant**
Fixes #168 

The so-called "dropbox directories" (a.k.a ftp folders) for a collection weren't being created with group write permissions. This meant that after a collection was created, Tai-chun needed to manually change the permissions on the directory.

This patch causes the dropbox directories to get created with 775 permissions.

### CODE REVIEW

File: app/models/admin/collection.rb [hunk 1]
```diff
@@ -230,7 +230,10 @@ def create_dropbox_directory!
       
       unless File.directory?(absolute_path)
         begin
-          Dir.mkdir(absolute_path)
+          old_umask = File::umask
+          File::umask(0002)
```
Comment (mbarnett) [inline app/models/admin/collection.rb]: Can I suggest adding a comment explaining why you're caching the old umask, changing it for one call, and then restoring it? I'll be lost and have to reconstruct your motivation from guesswork, if I ever have to tweak this code.

Also it might be useful to leave symbolic versions of the octal permissions in the comments. 0775 is rwxrwxr-x, for those playing the home game.

File: spec/models/collection_spec.rb [hunk 2]
```diff
@@ -501,10 +501,28 @@
...
+      collection.name = 'african art'
+      dropbox_dir = File.join(Avalon::Configuration.lookup('dropbox.path'), 'african_art')
+
+      collection.send(:create_dropbox_directory!)
+      expect(File.exists?(dropbox_dir)).to be_truthy
+
+      fstat = File.stat(dropbox_dir)
+      # This is mildly gross. Convert the file mode to a string (representing octal number),
+      # grab the last 3 chars for the UNIX style mode we expect.
+      expect(fstat.mode.to_s(8)[-3..-1]).to eq("775")
```
Comment (mbarnett) [inline spec/models/collection_spec.rb]: You could lose the string hack and just compare directly to the expected octal:

```ruby
expect(fstat.mode).to eq 0O40775
```

0O is the prefix for octal literals, and the "extraneous" high bit `4` is actually a part of your expectation -- that `dropbox_dir` _is_ a dir, and has it's directory bit set.

**Comment by cwant** [comment]
Thanks for your comments Matt. I've updated the code/spec to include your suggestions.
