### PR TITLE
Issue #76, fix facet text wrapping in chrome.

### LINKED ISSUE #76: Text wrapping in Chrome browser
### Descriptive summary
PROD Not sure if this is browser version specific or not (Chrome Version 56.0.2924.76), but there is some undesirable text wrapping in the browse facets, for example:
image

image

image

### Expected behavior
Text wrapping should be consistent between major browsers, and numbers/shorter text should not wrap over to next line

### Steps to reproduce the behavior

1. View browse facets in Chrome

### PR DESCRIPTION
**Pull request by cwant**
Avalon does some "smart" stuff in javascript to fudge the width
of facet labels and their counts (apparently the upstream Avalon
has had problems in the past ([1], [2]) with bad wrapping for
facet labels).

Adding a 2 pixel fudge factor for the facet count seems to fix
the problems reported in this issue. This fix isn't ideal,
since it has a "works for me" smell about it, so a full fix
might be an iterative process.

Here is before:

issue_76_before

Here is after:

issue_76_after

[1] https://github.com/avalonmediasystem/avalon/pull/578
[2] https://github.com/avalonmediasystem/avalon/pull/578/commits/651093725c85d245f6509eccc61f17189d3af679

Fixes #76

### CODE REVIEW

File: app/assets/javascripts/avalon.js [hunk 1]
```diff
@@ -25,7 +25,8 @@ $(document).ready(function() {
       var longest = $(this).find('.facet-count span').sort(longer).first();
       var clone = longest.clone().css('visibility','hidden');
       $('body').append(clone);
-      $(this).find('.facet-count').first().width(clone.width());
+      // U of A: add 2 pixel fudge factor to avoid bad number wrapping
+      $(this).find('.facet-count').first().width(clone.width()+2);
```
Comment (murny) [inline app/assets/javascripts/avalon.js]: This seems insane? They are using bootstrap panels for the facet themselves, why not do this smart? Like using list-groups and badges or something (which are floated right and will automatically expand accordingly)? 
http://getbootstrap.com/components/#panels-list-group
http://getbootstrap.com/components/#list-group-badges

Instead they wrote all custom css stuff using `display: table-cell` and hacking this in javascript to get this to look nice....sigh :-1: .

Might be more work to do it correctly. So this "hack" is fine.

Only complaint is your magic number of `2`. Maybe assign this to a variable so this is easily readable and refactorable for the next developer guessing what this special number is for? More info about this here: http://eslint.org/docs/rules/no-magic-numbers
