### PR TITLE
Issue #60 (see also #61). Allow editors to unpublish media objects.

### LINKED ISSUE #60: editor role is not working properly
### Descriptive summary

When we assign someone as an editor, the user is not able to make changes in the metadata

### Expected behavior
A user assigned with "editor" role for a particular collection should be able to make changes to metadata.

### Actual behavior
Currently an "editor" is not able to make metadata changes and save them. To overcome this, we have been assigning "manager" role which give them more power than we would like.

### Related work

#61

### PR DESCRIPTION
**Pull request by cwant**
This change is documented in our wiki:

https://github.com/ualbertalib/avalon/wiki/Customizations

Fixes #60 ; refs #61

### CODE REVIEW

File: app/models/ability.rb [hunk 1]
```diff
@@ -86,7 +86,7 @@ def custom_permissions(user=nil, session=nil)
         end
 
         can :unpublish, MediaObject do |mediaobject|
-          @user.in?(mediaobject.collection.managers)
+          is_editor_of?(mediaobject.collection)
```
Comment (weiweishi) [inline app/models/ability.rb]: Does this change mean manager can no longer unpublish? Should this be a ``&&`` statement?

Comment (cwant) [inline app/models/ability.rb]: "is_editor_of?" includes managers, see here:

https://github.com/ualbertalib/avalon/blob/master/app/models/ability.rb#L187
